### ISSUE TITLE
Functionality Issues and Missing Documentation

### ISSUE THREAD

**Issue by kuhmhe** [Sphinx-Galaxy/crt#2]
Hi, 

I am considering using this test suite for some radiation testing for my master thesis at the DLR and I am currently experiencing some problems with the Setup. 

As a first point, a documentation is mentioned in the readme, but is not part of the repository (I have gotten the file anyway, but just to let you know)
For the Setup of the LabJack: 
- the usage of the config files doesn't work. The program shows the correct amount of channels but the names are usually messed up and no values are shown at all. What is "con=2" used for in your example config file? It is not mentioned in the documentation. The example config file also differs from the description in the documentation as there is an id in the example.
- the manual configuration of the inputs also doesn't work. Values are shown, but they don't seem to make any sense, as the values also don't change that much when the device is disconnected completely. What is the input for "Connection" and "Identifier" within the manual setup? These are not mentioned in the documentation
![grafik](https://user-images.githubusercontent.com/108886486/185732301-4ff61ec2-44db-492d-bc71-eef3f5469f3a.png)
![grafik](https://user-images.githubusercontent.com/108886486/185732371-97541680-3dd6-41b7-9439-eea477cc28d1.png)
- which form of connection (USB, Ethernet) works for the labjack and how can that be set?

Thank you very much and with best regards, 
Hendrik Kuhm

**Comment by Sphinx-Galaxy** [comment]
Hey, thanks for the Feedback.

The documentation has now been added and updated accordingly, at least functionality wise. The 'manual configuration' via the GUI will probably still not work, because nobody has used this feature ever and I did every configuration via the config file. So its kinda depcerated...
For the labjack channels there was just a missing parameter in the example configuration. The 'range' was missing as it was only added recently after the last testrun. Its basically the labjack voltage measurement ranges (0.01, 0.1, 1, 10). Just keep it at 10.

The connection or "con=*" is the connection type, refer to the Labjack opening function (https://labjack.com/support/software/api/ljm/function-reference/opening-and-closing). Basically '1' is for USB and '3' for ethernet as far as i see. And the Identifier is then either the IP address or the device id.

The values might not make sense as there is a 'self test' function in there. Just disable the flag 'DUMMY_DATA' in the qt project file. (Its now also mentioned in the README.md)

**Comment by kuhmhe** [comment]
Hi, 
thanks for the quick answer! We got the LabJack running but could not find the option to disable the flag in the qt project file. We found a workaround, but maybe a more detailed description would be helpful. 

I did also have a problem connecting the PSU to the program. We are using a HMC8043, which the program should support.  When using the example configuration file, an error showed up: 
![grafik](https://user-images.githubusercontent.com/108886486/186441173-d4a1ec01-5817-419f-b254-8f54ca426d1e.png)
How do I have to adapt the config file for this to work? 
With the manual setup, the program shows three channels, but nothing that is set in the program is transferred to the PSU. 

I wanted to have an "oscillating" power level for my tests that constantly varies between multiple voltage levels. 
Is there an option for this already included in the program? 

Thanks again for the support!

**Comment by Sphinx-Galaxy** [comment]
For the config parser, there was something wrong in the program logic. It's fixed now and has some additional information in case someone writes a wrong config.

With problems connecting to the PSU, i cannot really help, because i don't have a PSU here. But if you can give more details like IP adresse, wireshark packages, etc, i can take a look.

For the varying voltage levels I don't see a use case there. Especially not oscillating, because Powersupplies are made to feed constant voltage/current.

Regarding the dummy_data flag, there is no better description. And if you can't find it, just use grep, because a flag in general has a 'define' in front:
```
grep -rni -e "define.*dummy_data"
configurable-radiation-testsuite.pro:14:DEFINES += DUMMY_DATA
```

**Comment by kuhmhe** [comment]
Hi, 

ich würde der Einfachheit halber mal auf Deutsch wechseln. 
Inzwischen habe ich auf das DLR-interne Repo gewechselt, da in dieser öffentlichen Version es nicht möglich war, mehrere Labjacks auf einmal anzusteuern. 
Die Probleme mit der PSU-Ansteuerung bleiben allerdings auch mit dem DLR Repo bestehen. 
Die PSU kann angepingt werden, die IP-Adresse wurde manuell eingestellt. Es wurden einige Dinge ausprobiert, allerdings hat die PSU nie reagiert. Ich bin aktuell mit Ubuntu unterwegs, falls das das Problem sein sollte. 

Ein weiteres Problem bzw. Unklarheit ist die Einstellung der Messfrequenz im Labjack-Reiter. 
- Was genau kann über "Settling" eingestellt werden? 
- Wie kann die Messfrequenz angepasst werden? Hier sind zwei Felder für die Datarate [S/s] in dem Programm vorhanden. Der zweite Wert kann nicht geändert werden, bei Ändern des ersten Werts wird der zweite Wert automatisch auf denselben Wert gesetzt. Damit ist die Frequenz wieder bei 1Hz. Wie kann das geändert werden?

Wenn du die Zeit und Lust dazu hast, können wir uns auch gerne einmal in einem Call zusammen setzen um ein paar Dinge auszuprobieren. 

Danke und schöne Grüße

**Comment by Sphinx-Galaxy** [comment]
Moin,

das Problem mit den mehreren Labjack Instanzen ist behoben. Ich hatte wohl damals beim Refactoring gehofft, dass 'foreach' Referenzen und keine Kopien weitergibt.
Die Einstellungen beim Labjack sind im Grunde nur ein Wrapper für alles was Labjack selber schon bereitstellt. Z.b. die Settling Time: https://labjack.com/support/app-notes/SettlingTime. Gleiches gilt für alles andere dort. Im Normalfall kann man die Standardwerte beibehalten sofern man nichts besonderes machen will. Die Datenrate hab ich selber verbrochen, das linke Feld ist zum Einstellen und das rechte gibt die echte Datenrate an. Beispielsweise kann es passieren, dass man zuviele Eingänge abfragt und die Datenrate dann unter die gewünschte Menge fällt, also wenn 100 S/s gewünscht sind aber nur die Hälfte erreicht wird würde dort 100 / 50 stehen. Der Grund für diese 'Besonderheit' ist, dass bei hohen Datenrate diese nicht unbedingt die ganze Zeit aufrecht erhalten werden kann und gelegentlich mal abfällt und später wieder auf den eingestellt Wert zurückgesetzt wird.

Also wenn die PSU auch im DLR Repository nicht ansprechbar sind dann liegt der Fehler höchstwahrscheinlich nicht in der CRT. Ich hab die Erfahrung gemacht, dass auf neueren Systemen (damals ein Arch Linux), die LXI-Library nicht richtig funktioniert. Alternativ kann man auch mal das Docker Image probieren was beiliegt. Dort muss man nur eventuell einen Port weiterreichen für das PSU.

Können uns gerne mal zusammensetzen, bin nur zur Zeit etwas ausgelastet und erst Abends verfügbar. Email Kontakt ist: sphinx@galaxy-gate.de
